services:
  postgres:
    image: postgres:15
    container_name: pql-stock-tracker-container
    restart: always
    environment:
      POSTGRES_DB: pql-stock-tracker-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pg-stock-tracker-v:/var/lib/postgresql/data

volumes:
  pg-stock-tracker-v: 
